# Add project specific ProGuard rules here.
# Retrofit + kotlinx.serialization: keep serializers generated by the compiler plugin.
-keepattributes *Annotation*, InnerClasses, Signature, EnclosingMethod

# kotlinx.serialization
-keepclassmembers class **$$serializer { *; }
-keepclasseswithmembers class id.my.mymoney.** {
    kotlinx.serialization.KSerializer serializer(...);
}
